name: pycaret-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pycaret=3.0.0
  - numpy=1.24.4
  - pandas=1.5.3
  - scikit-learn
  - lightgbm
  - xgboost
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook
  - ipywidgets
  